<a href="https://colab.research.google.com/github/pedrosampaiom2007-gif/1CCPF-Python-FIAP-2026/blob/main/Pandas_I_O_estudo_peu_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Lendo e Salvando Arquivos CSV

Esta seção foca em como ler dados de arquivos CSV (Comma Separated Values) para DataFrames Pandas e como salvar DataFrames de volta em arquivos CSV. CSV é um formato comum para armazenar dados tabulares.

### 📖 Como funciona a leitura de CSV com Pandas?

O **Pandas** é a principal biblioteca do Python para análise de dados. Quando usamos a função `pd.read_csv(url)`, estamos trazendo uma tabela de dados da internet (ou do seu computador) para dentro do Python na forma de um **DataFrame** (que é o nome técnico para tabelas no Pandas).

In [ ]:
# Importa a biblioteca Pandas, que é usada para carregar, manipular e analisar tabelas de dados
import pandas as pd

In [ ]:
# Guarda o link da internet onde o arquivo CSV está salvo
url='https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/superstore_data.csv'

# Lê o arquivo de texto (CSV) da internet e o transforma em uma tabela (DataFrame) do Pandas, indicando que as colunas são separadas por vírgula
dados_mercado=pd.read_csv(url,sep= ',')

# Mostra na tela apenas as 5 primeiras linhas da tabela para visualizarmos a estrutura
dados_mercado.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
# Lê o arquivo CSV da internet, mas carrega apenas as primeiras 10 linhas para economizar memória
dados_primeiras_linhas=pd.read_csv(url,sep= ',', nrows=10)

# Exibe a tabela gerada com as 10 linhas carregadas
dados_primeiras_linhas

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
5,7348,1958,PhD,Single,71691,0,0,3/17/2014,0,336,...,240,32,43,1,4,7,5,2,1,0
6,4073,1954,2n Cycle,Married,63564,0,0,1/29/2014,0,769,...,15,34,65,1,10,10,7,6,1,0
7,1991,1967,Graduation,Together,44931,0,1,1/18/2014,0,78,...,0,0,7,1,2,1,3,5,0,0
8,4047,1954,PhD,Married,65324,0,1,11/1/2014,0,384,...,21,32,5,3,6,2,9,4,0,0
9,9477,1954,PhD,Married,65324,0,1,11/1/2014,0,384,...,21,32,5,3,6,2,9,4,0,0

In [ ]:
# Lê o arquivo CSV trazendo apenas as colunas específicas que passamos na lista: 'Id', 'Year_Birth' e 'Income'
dados_selecao=pd.read_csv(url,sep= ',', nrows=10,usecols=['Id','Year_Birth','Income'])

# Exibe a tabela filtrada
dados_selecao

      Id  Year_Birth  Income
0   1826        1970   84835
1      1        1961   57091
2  10476        1958   67267
3   1386        1967   32474
4   5371        1989   21474
5   7348        1958   71691
6   4073        1954   63564
7   1991        1967   44931
8   4047        1954   65324
9   9477        1954   65324

In [ ]:
# Carrega o CSV trazendo apenas a primeira coluna (índice 0) e a quarta coluna (índice 3)
dados_selecao=pd.read_csv(url,sep= ',', nrows=10,usecols=[0,3])

# Exibe o resultado obtido
dados_selecao

      Id Marital_Status
0   1826       Divorced
1      1         Single
2  10476        Married
3   1386       Together
4   5371         Single
5   7348         Single
6   4073        Married
7   1991       Together
8   4047        Married
9   9477        Married

### Salvando DataFrames em Arquivos CSV

Aqui demonstramos como salvar um DataFrame Pandas em um arquivo CSV local. É uma operação fundamental para persistir dados processados ou filtrados.

In [ ]:
# Salva a tabela 'dados_selecao' em um novo arquivo CSV no seu ambiente do Colab
dados_selecao.to_csv('clientes_mercado.csv')

In [ ]:
# Lê o arquivo CSV que acabamos de salvar localmente no Colab
clientes_mercado=pd.read_csv('/content/clientes_mercado.csv')

# Exibe o conteúdo do arquivo carregado
clientes_mercado

   Unnamed: 0     Id Marital_Status
0           0   1826       Divorced
1           1      1         Single
2           2  10476        Married
3           3   1386       Together
4           4   5371         Single
5           5   7348         Single
6           6   4073        Married
7           7   1991       Together
8           8   4047        Married
9           9   9477        Married

In [ ]:
# Salva os dados em um novo arquivo CSV, mas sem salvar a coluna de índices numéricos gerada automaticamente
dados_selecao.to_csv('dados_mercado.csv',index=False)

In [ ]:
# Lê novamente o arquivo CSV salvo sem a coluna de índices indesejada
dados_mercado=pd.read_csv('/content/dados_mercado.csv')

# Exibe a tabela limpa
dados_mercado

      Id Marital_Status
0   1826       Divorced
1      1         Single
2  10476        Married
3   1386       Together
4   5371         Single
5   7348         Single
6   4073        Married
7   1991       Together
8   4047        Married
9   9477        Married

### Parâmetros Avançados para Leitura de CSV

Ao ler arquivos CSV, é comum precisar de mais controle sobre o processo. Alguns parâmetros importantes incluem:

*   `skiprows`: Permite pular um número específico de linhas do início do arquivo (por exemplo, cabeçalhos ou metadados).
*   `skipfooter`: Permite pular um número específico de linhas do final do arquivo (útil para rodapés ou comentários). **Nota**: `skipfooter` geralmente requer o `engine='python'` para funcionar corretamente, pois o motor C padrão do Pandas não suporta essa funcionalidade.
*   `encoding`: Define a codificação de caracteres do arquivo (ex: 'ISO-8859-1', 'utf-8'). Arquivos com codificações diferentes podem causar erros na leitura se o `encoding` não for especificado corretamente.
*   `sep`: Define o delimitador de colunas no arquivo CSV (por exemplo, ',' para vírgula, ';' para ponto e vírgula).

### ⚙️ Parâmetros importantes de leitura

Quando os dados são muito grandes ou possuem formatos especiais, usamos alguns ajustes de configuração:
* **`skiprows`**: Pula linhas inúteis no início do arquivo (como cabeçalhos de relatórios).
* **`skipfooter`**: Ignora observações ou resumos ao final do arquivo.
* **`encoding`**: Ajuda o Python a ler acentos e caracteres especiais da língua portuguesa corretamente (ex: `ISO-8859-1`).

In [ ]:
# URL contendo os dados do SUS no GitHub
url='https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'

# Carrega os dados com configurações avançadas:
# - encoding='ISO-8859-1' para ler caracteres especiais em português corretamente
# - skiprows=3 para pular as 3 primeiras linhas de cabeçalho do arquivo
# - skipfooter=9 para ignorar as últimas 9 linhas de rodapé do arquivo
# - sep=';' define o ponto e vírgula como separador
# - engine='python' é necessário para poder usar o skipfooter
dados=pd.read_csv(url,encoding='ISO-8859-1',skiprows=3,skipfooter=9,sep=';',engine='python')

# Exibe as 5 primeiras linhas da tabela processada
dados.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"

### Lendo Arquivos Excel

Esta seção aborda a leitura de dados de arquivos Excel (`.xlsx` ou `.xls`) para DataFrames Pandas. Arquivos Excel são frequentemente usados para armazenamento de dados tabulares e relatórios.

### 📊 Lendo tabelas do Excel (`.xlsx`)

Arquivos Excel diferem de arquivos CSV por poderem ter múltiplas abas (planilhas internas). No Pandas, usamos `pd.read_excel()` para carregar estes arquivos. Caso queira escolher uma aba específica, basta usar o parâmetro `sheet_name` informando o nome da aba desejada.

### Dica para Acesso a Arquivos "Raw" no GitHub

Ao tentar ler arquivos diretamente do GitHub (ou outros repositórios Git), a URL padrão pode não ser a URL do arquivo "raw". Para garantir que o Pandas (ou outras bibliotecas) consiga ler o conteúdo do arquivo corretamente, adicione `?raw=True` ao final da URL do arquivo no GitHub. Isso força a entrega do conteúdo bruto do arquivo.

In [ ]:
# Armazena o link do arquivo Excel hospedado no GitHub, usando o final '?raw=True' para baixar o arquivo correto
url='https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [ ]:
# Usa o Pandas para ler o arquivo Excel carregado a partir do link fornecido
dados_co2=pd.read_excel(url)

In [ ]:
# Exibe as primeiras 5 linhas da tabela de emissões de CO2 carregada do Excel
dados_co2.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Verificando Múltiplas Abas em Arquivos Excel

Arquivos Excel podem conter múltiplas abas (sheets). Para listar todas as abas disponíveis em um arquivo Excel antes de lê-lo, você pode usar `pd.ExcelFile(url).sheet_names`. Isso é útil para entender a estrutura do arquivo e selecionar a aba correta.

In [ ]:
# Abre o arquivo Excel e lista os nomes de todas as abas (planilhas internas) existentes nele
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

### Lendo uma Aba (Sheet) Específica de um Arquivo Excel

Para carregar dados de uma aba específica de um arquivo Excel, utilize o parâmetro `sheet_name` na função `pd.read_excel()`. Você pode especificar o nome da aba como uma string ou seu índice (onde 0 é a primeira aba).

In [ ]:
# Lê a aba específica chamada 'emissoes_percapita' de dentro do nosso arquivo Excel
percapita=pd.read_excel(url,sheet_name='emissoes_percapita')

# Nota explicativa alternativa: pd.read_excel(url,sheet_name='0') carregaria a primeira aba pelo índice

In [ ]:
# Mostra as primeiras 5 linhas da tabela de emissão de CO2 per capita
percapita.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Lê outra aba específica chamada 'fontes' do mesmo arquivo Excel
fontes=pd.read_excel(url,sheet_name='fontes')

# Exibe o início da tabela carregada da aba 'fontes'
fontes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

In [ ]:
# Carrega a aba chamada 'emissoes_C02' do nosso arquivo do Excel
emissoes=pd.read_excel(url,sheet_name='emissoes_C02')

# Mostra o cabeçalho e as primeiras linhas dessa aba específica
emissoes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Lendo Colunas Específicas de uma Aba (Sheet) no Excel

É possível carregar apenas um subconjunto de colunas de uma aba específica de um arquivo Excel usando o parâmetro `usecols`. Você pode especificar as colunas por nome ou por um intervalo de colunas no formato Excel (ex: 'A:D').

In [ ]:
# Lê a aba 'emissoes_C02' trazendo apenas o intervalo de colunas de 'A' até 'D'
intervalo=pd.read_excel(url,sheet_name='emissoes_C02',usecols='A:D')

# Mostra as primeiras 5 linhas com apenas esse intervalo selecionado
intervalo.head()

          País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750    0.0
1  Afeganistão                AFG  1751    0.0
2  Afeganistão                AFG  1752    0.0
3  Afeganistão                AFG  1753    0.0
4  Afeganistão                AFG  1754    0.0

In [ ]:
# Lê apenas o intervalo de colunas de 'A' até 'D' e limita o carregamento para apenas as primeiras 10 linhas da tabela
intervalo_2=pd.read_excel(url,sheet_name='emissoes_C02',usecols='A:D',nrows=10)

# Mostra o resultado final limitado
intervalo_2.head()

          País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0

### Salvando DataFrames em Arquivos Excel

Para salvar um DataFrame Pandas em um novo arquivo Excel, utilize o método `.to_excel()`.

*   O parâmetro `index=False` é crucial para evitar que o índice do DataFrame seja salvo como uma coluna adicional no arquivo Excel, o que geralmente não é desejado.

In [ ]:
# Exporta e salva o DataFrame 'percapita' no formato de arquivo Excel (.xlsx), ignorando a coluna de índices numéricos
percapita.to_excel('percapita.xlsx',index=False)

In [ ]:
# Lê o arquivo Excel local criado anteriormente para testar se foi salvo corretamente
pd.read_excel('/content/percapita.xlsx')

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

### Lendo Dados de Planilhas Google (Google Sheets)

Esta seção demonstra como ler dados diretamente de Planilhas Google para um DataFrame Pandas. Isso é particularmente útil para colaboração e acesso a dados que são mantidos online.

In [ ]:
# Linha de comentário contendo o link de compartilhamento original da planilha do Google Sheets
#https://docs.google.com/spreadsheets/d/1LrO7G2SN1LEdsLK67jU9Tcs2IdAe0OYjKKv0otVtD5s/edit?usp=sharing

### Conectando a Planilhas Google via API e Formato CSV

Para permitir que o Colab (ou qualquer ferramenta externa) leia dados de uma Planilha Google como se fosse um arquivo CSV, utilizamos um endpoint especial do Google Sheets API. O parâmetro `gviz/tq?tqx=out:csv&sheet` na URL é fundamental:

*   `gviz/tq`: Indica que estamos fazendo uma requisição ao Google Visualization API Query.
*   `tqx=out:csv`: Especifica que a saída desejada é no formato CSV.
*   `sheet`: (opcional) Permite especificar qual aba (sheet) da planilha deve ser lida. Se omitido, a primeira aba será usada.

In [ ]:
# Identificador exclusivo (ID) da planilha compartilhada do Google Sheets
sheet_id='1LrO7G2SN1LEdsLK67jU9Tcs2IdAe0OYjKKv0otVtD5s'

In [ ]:
# Monta a URL especial do Google API que exporta a planilha de forma direta no formato de arquivo texto CSV
url=f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
# Lê a planilha diretamente da URL formatada como se fosse um arquivo CSV padrão
dados_co2_sheets=pd.read_csv(url)

In [ ]:
# Define o ID da planilha do Google Sheets
sheet_id='1LrO7G2SN1LEdsLK67jU9Tcs2IdAe0OYjKKv0otVtD5s'

# Informa o nome exato da aba que queremos ler da planilha
sheet_name='emissoes_percapita'

# Cria a URL adicionando o nome da aba desejada no final
url_percapita=f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

# Carrega a aba selecionada em um DataFrame do Pandas e exibe as 5 primeiras linhas
percapita_sheets=pd.read_csv(url_percapita)
percapita_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Define o ID da planilha do Google Sheets
sheet_id='1LrO7G2SN1LEdsLK67jU9Tcs2IdAe0OYjKKv0otVtD5s'

# Informa o nome da aba 'emissoes_C02'
sheet_name='emissoes_C02'

# Monta a URL de exportação para CSV indicando a aba 'emissoes_C02'
url_C02=f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

# Lê os dados e mostra os primeiros 5 registros na tela
c02_sheets=pd.read_csv(url_C02)
c02_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Prática: Lendo Planilhas Google com Aba Específica

Esta seção serve como um exercício prático para aplicar o conhecimento adquirido sobre como ler dados de Planilhas Google, especificando uma aba (sheet) diferente da padrão.

In [ ]:
# Link para a nova Planilha Google utilizada na atividade prática
#https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/edit?gid=1214654498#gid=1214654498

In [ ]:
# Define o ID da nova Planilha Google
sheet_id='1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'

# Define a aba contendo as informações de emissões de CO2
sheet_name='C02_emission'

# Monta a URL de conexão para ler os dados no formato de texto CSV
url_nova=f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

# Carrega a planilha externa usando a biblioteca Pandas
dados_novos=pd.read_csv(url_nova)

# Exibe as primeiras 5 linhas
dados_novos.head()

,Country,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432

In [ ]:
# Salva o DataFrame carregado 'dados_novos' no formato CSV local, ocultando os índices do Pandas
dados_novos.to_csv('dados_novos.csv',index=False)

### Trabalhando com Dados JSON

JSON (JavaScript Object Notation) é um formato de dados leve e muito utilizado para troca de informações entre sistemas. Esta seção aborda como ler e manipular dados no formato JSON com Pandas.

### 🕸️ O que é JSON e como lê-lo?

O **JSON** é um formato leve e muito comum para transferir dados na internet. Muitas vezes os dados vêm aninhados (uma informação dentro da outra, como um dicionário). Para converter de forma plana em uma tabela limpa com linhas e colunas estruturadas, usamos o recurso **`pd.json_normalize()`**.

In [ ]:
# Importação de segurança da biblioteca Pandas para garantir que esteja ativa
import pandas as pd

In [ ]:
# Lê o arquivo de dados em formato JSON e o converte para uma tabela utilizável
dados_paciente=pd.read_json("/content/pacientes.json")

# Exibe toda a tabela de pacientes na tela
dados_paciente

,ID_paciente,Doenca_cardiaca,IMC,Fumante,Consumo_alcool,AVC,Saude_fisica,Saude_mental,Dificuldade_caminhar,Sexo_biologico,Faixa_etaria,Raca,Diabetes,Atividade_fisica,Saude_geral,Horas_sono,Asma,Doenca_renal,Cancer_pele
0,0,Nao,16.60,Sim,Nao,Nao,3,30,Nao,Feminino,55-59,Branca,Sim,Sim,Muito boa,5,Sim,Nao,Sim
1,1,Nao,20.34,Nao,Nao,Sim,0,0,Nao,Feminino,80 ou +,Branca,Nao,Sim,Muito boa,7,Nao,Nao,Nao
2,2,Nao,26.58,Sim,Nao,Nao,20,30,Nao,Masculino,65-69,Branca,Sim,Sim,Razoavel,8,Sim,Nao,Nao
3,3,Nao,24.21,Nao,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,No,Boa,6,Nao,Nao,Sim
4,4,Nao,23.71,Nao,Nao,Nao,28,0,Sim,Feminino,40-44,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Nao,28.29,Sim,Nao,Nao,10,20,Nao,Feminino,65-69,Preta,Sim,Sim,Razoavel,8,Nao,Nao,Nao
996,996,Nao,25.69,Sim,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,Sim,Excelente,8,Nao,Nao,Nao
997,997,Sim,26.99,Nao,Nao,Nao,1,0,Nao,Masculino,70-74,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
998,998,Nao,44.29,Nao,Nao,Nao,30,0,Sim,Feminino,70-74,Branca,Sim,No,Boa,6,Sim,Nao,Nao
999,999,Nao,25.83,Nao,Nao,Nao,0,0,Nao,Masculino,70-74,Preta,Sim,No,Excelente,7,Nao,Nao,Nao

In [ ]:
# Carrega um segundo arquivo JSON que possui uma estrutura interna aninhada (objetos dentro de objetos)
dados_paciente_2=pd.read_json("/content/pacientes_2.json")

# Exibe a tabela mostrando como as informações internas ficam compactadas em uma única coluna
dados_paciente_2

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

### Normalizando Dados JSON Aninhados

Frequentemente, dados JSON vêm com estruturas aninhadas (objetos dentro de outros objetos). Para transformar esses dados aninhados em uma estrutura tabular plana adequada para DataFrames Pandas, usamos a função `pd.json_normalize()`. Isso é essencial para facilitar a análise de dados complexos.

In [ ]:
# Desmembra a coluna 'Pacientes' que continha dados aninhados (dicionários) e os espalha em colunas individuais organizadas
df_dados=pd.json_normalize(dados_paciente_2["Pacientes"])

# Exibe a tabela normalizada de forma limpa e organizada
df_dados

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

### Salvando DataFrames em Arquivos JSON

Após processar e normalizar dados JSON, pode ser necessário salvá-los de volta em um arquivo JSON. O método `.to_json()` do Pandas permite exportar um DataFrame para esse formato.

In [ ]:
# Salva o DataFrame normalizado em um arquivo no formato JSON no ambiente local
df_dados.to_json("dados_normalizados.json")

### Consumindo APIs com Respostas JSON

Muitos serviços web (APIs) retornam dados no formato JSON. Esta seção mostra como fazer requisições a uma API, obter a resposta em JSON e convertê-la em um formato utilizável pelo Pandas.

In [ ]:
# Importa a biblioteca 'requests' para fazer requisições a sites e APIs na web
import requests

# Importa a biblioteca padrão 'json' para lidar com estruturas de dados JSON do Python
import json

### Obtendo Dados de uma API Externa com `requests.get()`

Para interagir com APIs RESTful e obter dados, usamos a biblioteca `requests` do Python, especificamente a função `requests.get()`. Basta passar a URL do endpoint da API como argumento para essa função.

In [ ]:
# Faz uma requisição GET para acessar os dados de usuários de uma API de testes pública
dados_usuarios = requests.get('https://jsonplaceholder.typicode.com/users')

### Convertendo Resposta de API para Objeto Python (JSON)

A resposta de uma requisição `requests.get()` geralmente vem como uma string de texto. Se a API retorna JSON, precisamos converter essa string JSON em um objeto Python (como um dicionário ou lista de dicionários) usando `json.loads()`. O atributo `.text` do objeto de resposta `dados_usuarios` contém a string JSON.

In [ ]:
# Converte o texto retornado da API (que é um JSON bruto) para um objeto de listas e dicionários nativos do Python
resultado = json.loads(dados_usuarios.text)

### Visualizando os Dados da API em um DataFrame

Após converter a resposta JSON da API para um objeto Python, podemos facilmente transformá-lo em um DataFrame Pandas para visualização e análise.

In [ ]:
# Transforma o objeto Python obtido da API diretamente em uma tabela do Pandas
pd.DataFrame(resultado)

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

### Prática: Normalizando Dados JSON de API

Esta seção é um exercício para praticar a normalização de dados JSON obtidos de uma API. A normalização é fundamental para transformar estruturas de dados complexas em tabelas planas para análise.

In [ ]:
# Faz uma nova requisição à API para baixar as informações atualizadas de usuários
dados=requests.get("https://jsonplaceholder.typicode.com/users")

In [ ]:
# Converte o texto cru da resposta JSON obtido da API em uma lista/dicionário Python estruturado
resultado = json.loads(dados_usuarios.text)

### Dica de Normalização: Usando `sep='_'` em `pd.json_normalize()`

Ao normalizar JSONs com `pd.json_normalize()`, o argumento `sep='_'` é extremamente útil. Ele define o separador para os nomes das colunas aninhadas. Por exemplo, se você tem `{"address": {"street": "Main"}}`, com `sep='_'` a coluna se tornaria `address_street`. Isso ajuda a manter a clareza e a evitar colisões de nomes, tornando os dados mais fáceis de acessar e manipular.

In [ ]:
# Desmembra o JSON aninhado criando colunas separadas por Underline (_) para os campos internos (como rua, cidade e geolocalização)
normal=pd.json_normalize(resultado,sep="_")

# Exibe o DataFrame resultante plano e estruturado
normal

,id,name,username,email,phone,website,address_street,address_suite,address_city,address_zipcode,address_geo_lat,address_geo_lng,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

### Trabalhando com Dados HTML

Esta seção explora como extrair tabelas de páginas web ou arquivos HTML usando o Pandas. Isso é conhecido como "web scraping" de tabelas.

In [ ]:
# Certifica-se de que a biblioteca Pandas esteja importada para poder trabalhar com tabelas
import pandas as pd

In [ ]:
# Varre o arquivo HTML local procurando por tabelas contidas nas tags <table> e as converte em uma lista de DataFrames
dados_html=pd.read_html("/content/filmes_wikipedia.html")

# Exibe a lista contendo as tabelas encontradas
dados_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles
 1                     Casablanca          1942        Michael Curtiz
 2                  The Godfather          1972  Francis Ford Coppola
 3             Gone with the Wind          1939        Victor Fleming
 4             Lawrence of Arabia          1962            David Lean
 ..                           ...           ...                   ...
 95                 The Searchers          1956             John Ford
 96              Bringing Up Baby          1938          Howard Hawks
 97                    Unforgiven          1992        Clint Eastwood
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer
 99           Yankee Doodle Dandy          1942        Michael Curtiz

                       Production companies  Rank
 0                       RKO Radio Pictures     1
 1                    Warner Bros. Pictures     2
 2   Paramount Pictures, Alfran Productions     3
 3          Selznick International Pictures     4
 4                         Horizon Pictures     5
 ..                                     ...   ...
 95                  C. V. Whitney Pictures    96
 96                      RKO Radio Pictures    97
 97                     The Malpaso Company    98
 98                       Columbia Pictures    99
 99                   Warner Bros. Pictures   100

 [100 rows x 5 columns],
           hidevteAFI's 100 Years...100 Movies (1998)  \
 0  Citizen Kane (1941) Casablanca (1942) The Godf...

         hidevteAFI's 100 Years...100 Movies (1998).1
 0  Citizen Kane (1941) Casablanca (1942) The Godf...  ]

### Selecionando uma Tabela Específica de um Arquivo HTML por Índice

Quando o Pandas lê um arquivo HTML com `pd.read_html()`, ele retorna uma lista de todos os DataFrames encontrados (ou seja, todas as tabelas HTML). Para trabalhar com uma tabela específica, você precisa selecioná-la pelo seu índice na lista (0 para a primeira tabela, 1 para a segunda, e assim por diante).

In [ ]:
# Seleciona a segunda tabela encontrada na lista do HTML (índice 1) que contém a lista dos top filmes
top_filmes=dados_html[1]

# Exibe a tabela selecionada
top_filmes

,Film,Release year,Director,Production companies,Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5
...,...,...,...,...,...
95,The Searchers,1956,John Ford,C. V. Whitney Pictures,96
96,Bringing Up Baby,1938,Howard Hawks,RKO Radio Pictures,97
97,Unforgiven,1992,Clint Eastwood,The Malpaso Company,98
98,Guess Who's Coming to Dinner,1967,Stanley Kramer,Columbia Pictures,99
99,Yankee Doodle Dandy,1942,Michael Curtiz,Warner Bros. Pictures,100

### Salvando DataFrames em Arquivos HTML

O método `.to_html()` do Pandas permite exportar um DataFrame para um arquivo HTML. Isso pode ser útil para gerar relatórios web ou para visualizar dados em navegadores.

In [ ]:
# Exporta e salva a tabela 'top_filmes' gerada como um novo arquivo de página web HTML
top_filmes.to_html("top_filmes.html")

### Trabalhando com Dados XML

XML (eXtensible Markup Language) é outro formato de dados para armazenamento e transporte de informações. Esta seção mostra como ler dados de arquivos XML para DataFrames Pandas.

In [ ]:
# Lê as tags estruturadas do arquivo XML local e as organiza diretamente em colunas tabulares do Pandas
xml_data= pd.read_xml("/content/imdb_top_1000.xml")

# Exibe a tabela de dados XML
xml_data

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,None
996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,None
997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,None,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,None
999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,None,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,None

### Salvando DataFrames em Arquivos XML

Para persistir um DataFrame em formato XML, utiliza-se o método `.to_xml()`. Isso é útil quando a interoperabilidade com sistemas que esperam XML é necessária.

In [ ]:
# Salva as informações contidas no DataFrame de volta em um arquivo de tags XML
xml_data.to_xml("dados.xml")

## Trabalhando com Bancos de Dados

Esta seção introduz a interação com bancos de dados, focando em como criar, popular, consultar e manipular dados em um banco de dados SQL usando Pandas e SQLAlchemy.

### 🗄️ O que é um Banco de Dados Relacional e SQL?

Para trabalharmos com grandes volumes de dados de forma segura, guardamos as informações em bancos de dados. Com o auxílio do **SQLAlchemy**, conseguimos criar conexões e usar a linguagem **SQL** para interagir diretamente com as tabelas, permitindo fazer:
* **`SELECT`**: Consultar e trazer dados específicos.
* **`INSERT`**: Adicionar novos registros.
* **`UPDATE`**: Atualizar informações existentes.
* **`DELETE`**: Apagar registros.

### Criando um Banco de Dados SQLite em Memória

Usaremos a biblioteca SQLAlchemy para criar um banco de dados SQLite temporário, que reside apenas na memória (`:memory:`). Isso é ideal para testes e exemplos rápidos, pois o banco de dados é destruído quando a sessão é encerrada.

In [ ]:
### SQL: Structured Query Language

SQL (Structured Query Language) é a linguagem padrão para gerenciar e manipular bancos de dados relacionais. É usada para consultar, atualizar, inserir e deletar dados, além de gerenciar a estrutura do banco de dados.

In [ ]:
# Importa a biblioteca SQLAlchemy para conexão com bancos de dados relacionais
import sqlalchemy

# Importa a classe 'text' usada para escrever queries SQL puras de maneira segura
from sqlalchemy import text

In [ ]:
from sqlalchemy import (create_engine,# motor oq faz o banco de dados funcionar
 MetaData,# classe de metadados que representa o banco de dados
  Table,# classe que represneta tabela em um banco de dados de uma tabela especifica
   inspect)# inspecionar o banco de dados

In [ ]:
# Cria um motor (Engine) para gerenciar um banco de dados SQLite temporário e rápido que roda na memória RAM do computador
engine= create_engine("sqlite:///:memory")

### Escrevendo um DataFrame em um Banco de Dados Local

O Pandas, em conjunto com SQLAlchemy, facilita a escrita de um DataFrame inteiro para uma tabela em um banco de dados. O método `.to_sql()` é usado para essa finalidade.

In [ ]:
# Guarda a URL direta para o arquivo CSV de clientes de banco hospedado no GitHub
url='https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/clientes_banco.csv'

In [ ]:
# Carrega o CSV de clientes usando Pandas a partir do link
dados=pd.read_csv(url)

# Exibe os primeiros 5 cadastros para verificação inicial
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [ ]:
# Salva as informações do DataFrame em uma tabela SQL de nome 'clientes' no banco de dados SQLite, sem guardar a coluna de índice
dados.to_sql("clientes",engine,index=False)

ValueError: Table 'clientes' already exists.

In [ ]:
# Cria uma ferramenta inspect para examinar de perto as tabelas estruturadas no nosso banco de dados
inspector=inspect(engine)

### Validando a Criação da Tabela no Banco de Dados

Para confirmar que a tabela foi criada com sucesso no banco de dados, podemos usar o `inspector` do SQLAlchemy para listar todas as tabelas existentes.

In [ ]:
# Busca e imprime o nome de todas as tabelas criadas no banco de dados para checar se a tabela 'clientes' foi criada
print(inspector.get_table_names())

['clienta', 'cliente', 'clientes', 'empregados']

### Consultando Dados do Banco de Dados SQL

Uma vez que os dados estão no banco de dados, podemos usar o Pandas e SQLAlchemy para executar consultas SQL e carregar os resultados de volta para um DataFrame.

In [ ]:
# Cria uma consulta em SQL para selecionar apenas os registros da tabela clientes onde a categoria de renda seja igual a 'Empregado'
query="SELECT * FROM clientes WHERE Categoria_de_renda='Empregado' "

# Roda a consulta acima diretamente no banco usando o Pandas e salva o resultado em um novo DataFrame
empregados=pd.read_sql(query,engine)

In [ ]:
# Salva o subconjunto de empregados em uma nova tabela SQL física chamada 'empregados' dentro do nosso banco SQLite
empregados.to_sql("empregados",con=engine,index=False)

ValueError: Table 'empregados' already exists.

### Lendo uma Tabela Específica do Banco de Dados

O Pandas oferece a função `pd.read_sql_table()` para ler diretamente uma tabela inteira de um banco de dados, sem a necessidade de escrever uma consulta SQL completa, facilitando o acesso aos dados.

In [ ]:
# Lê de forma direta e rápida todos os dados salvos dentro da tabela 'empregados' do banco
pd.read_sql_table("empregados",engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

### Analisando Colunas Específicas de uma Tabela SQL

Podemos refinar a leitura de uma tabela SQL para incluir apenas um subconjunto de colunas, passando uma lista de nomes de colunas para `pd.read_sql_table()`. Isso é útil para otimizar o desempenho e carregar apenas os dados necessários.

In [ ]:
# Lê a tabela 'empregados' do banco, mas puxa apenas as colunas: 'ID_Cliente', 'Grau_escolaridade' e 'Rendimento_anual'
pd.read_sql_table("empregados",engine,columns=["ID_Cliente","Grau_escolaridade","Rendimento_anual"])

        ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

#Para deletar um registro na tabela clientes, agora utilizamos a seguinte estrutura:

In [ ]:
# Define a query SQL para remover o registro do cliente de ID 5008804
query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'

# Abre conexão com o banco, executa a exclusão de forma segura e confirma a transação com commit()
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

#Para atualizar...

In [ ]:
# Cria a query SQL para atualizar o grau de escolaridade do cliente correspondente ao ID 5008808 para 'Ensino superior'
query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'

# Conecta ao banco de dados SQLite, executa a atualização e finaliza gravando de forma permanente com o commit()
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

#PRÁTICA

In [ ]:
# Cria uma query para trazer todos os registros existentes na tabela clientes
query=' SELECT * FROM clientes'

In [ ]:
# Executa a consulta SQL anterior e mostra na tela todos os registros retornados em formato de DataFrame do Pandas
pd.read_sql(query,engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino superior,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008811,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438456,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438457,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438458,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438459,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438460,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
# Query SQL para deletar novamente o registro com ID 5008804 para validar a alteração
query= 'DELETE FROM clientes WHERE ID_Cliente=5008804'

# Conecta ao banco, executa o comando SQL e salva as alterações feitas no SQLite
with engine.connect() as conn:
  result= conn.execute(text(query))
  conn.commit()

In [ ]:
# Query SQL para re-confirmar a atualização da escolaridade do cliente 5008808 no banco
query= 'UPDATE  clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'

# Conecta e executa a transação SQL, confirmando logo em seguida
with engine.connect() as conn:
  result=conn.execute(text(query))
  conn.commit()

In [ ]:
import sqlalchemy
from sqlalchemy import text
from sqlalchemy import(create_engine,MetaData,Table,inspect)

In [ ]:
url='https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/clientes_banco.csv'

In [ ]:
# Inicializa o motor de banco de dados SQLite em memória exclusivo para a tabela de 'clienta'
engine= create_engine("sqlite:///:memory")

In [ ]:
# Lê os dados do arquivo CSV fornecido na URL de forma padrão no Pandas
dados_clienta=pd.read_csv(url)

In [ ]:
# Escreve e cria a tabela SQL 'clienta' com os dados carregados do DataFrame, ocultando colunas de índice
dados_clienta.to_sql("clienta",engine,index=False)

ValueError: Table 'clienta' already exists.

In [ ]:
# Cria instrução SQL para atualizar o rendimento anual do cliente ID 6840104 para 300.000
atualiza= 'UPDATE clientes SET Rendimento_anual=300000 WHERE ID_Cliente=6840104 '

# Conecta, executa a query e efetua o commit para aplicar de forma permanente
with engine.connect() as conn:
  result= conn.execute(text(atualiza))
  conn.commit()

### Verificando Alterações no Banco de Dados após Operações DML

Após realizar operações de DML (Data Manipulation Language) como `UPDATE` ou `DELETE` diretamente no banco de dados via SQLAlchemy, os DataFrames que foram carregados *antes* dessas operações não refletem automaticamente as mudanças. É necessário executar uma nova consulta para carregar os dados atualizados do banco de dados e verificar as alterações.

In [ ]:
# Consulta SQL de teste para trazer informações de ID, escolaridade e rendimento dos IDs alterados ou apagados
query_check = "SELECT ID_Cliente, Grau_escolaridade, Rendimento_anual FROM clientes WHERE ID_Cliente IN (5008808, 6840104, 5008804)"

# Carrega os resultados do banco em formato de DataFrame do Pandas
updated_clientes = pd.read_sql(query_check, engine)

# Exibe o resultado das alterações
display(updated_clientes)

# Nota: Você deve ver 'Ensino superior' para ID_Cliente 5008808 e '300000.0' para Rendimento_anual de ID_Cliente 6840104
# ID_Cliente 5008804 não deve aparecer caso o DELETE tenha sido efetuado com sucesso

   ID_Cliente Grau_escolaridade  Rendimento_anual
0     5008808   Ensino superior          270000.0
1     6840104      Ensino médio          300000.0

In [ ]:
# Define o comando em SQL para excluir o cliente com ID igual a 5008809 da tabela 'clienta'
deletar= 'DELETE FROM clienta WHERE ID_Cliente=5008809'

# Conecta ao banco de dados, executa a exclusão de registro e realiza commit das alterações
with engine.connect() as conn:
  result=conn.execute(text(deletar))
  conn.commit()

In [ ]:
# Define uma consulta SQL para checar se o ID apagado (5008809) ainda existe na tabela 'clienta'
check_2= " SELECT ID_Cliente FROM 'clienta' WHERE ID_Cliente=5008809"

# Roda a consulta e traz o resultado para o Pandas
updated_clientes = pd.read_sql(check_2, engine)

# Mostra a tabela (se o DELETE deu certo, deve vir vazia)
display(updated_clientes)

Empty DataFrame
Columns: [ID_Cliente]
Index: []

In [ ]:
inserir_novo = (
    'INSERT INTO clienta (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, '
    'Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, '
    'Rendimento_anual, Tem_carro, Moradia) '
    'VALUES (6850985, 34, "Doutorado", "Solteiro", 1, "Empregado", "TI", '
    '2, 290000, 0, "Casa/apartamento próprio")'
)

In [ ]:
# Executando a inserção no banco de dados
with engine.connect() as conn:
    conn.execute(text(inserir_novo))
    conn.commit()

In [ ]:
# Consulta SQL para buscar os dados de ID do novo cliente inserido (6850985)
check_3= " SELECT ID_Cliente FROM 'clienta' WHERE ID_Cliente=6850985"

# Executa o SELECT utilizando Pandas no banco SQLite
updated_clientes = pd.read_sql(check_3, engine)

# Exibe o resultado obtido do banco na tela
display(updated_clientes)

   ID_Cliente
0     6850985
1     6850985

In [ ]:
# Carrega por completo o conteúdo atualizado da tabela 'clienta' gravada no banco para verificar todas as linhas
pd.read_sql_table("clienta",engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,34,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio
438463,6850985,34,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio

### O que é um Banco de Dados?

Bancos de dados são sistemas que permitem o armazenamento, organização e recuperação de informações de forma estruturada e eficiente. Eles são amplamente utilizados em muitas áreas, desde gerenciamento de negócios à pesquisa científica. Um banco de dados bem projetado pode melhorar significativamente a eficiência e a precisão das operações de uma organização.

### Principais Cláusulas SQL (DQL - Data Query Language)

As instruções SQL para consulta de dados (DQL) são compostas por cláusulas que fornecem informações detalhadas sobre como os dados devem ser recuperados. As cláusulas mais comuns são:

*   `SELECT`: **O que** queremos ver. Especifica quais colunas devem ser selecionadas na consulta.
*   `FROM`: **De onde** vêm os dados. Especifica as tabelas do banco de dados que devem ser consultadas.
*   `WHERE`: **Quais** condições os dados devem atender. Filtra os resultados da consulta com base em uma ou mais condições especificadas.
*   `ORDER BY`: **Como** os resultados devem ser ordenados. Classifica os resultados da consulta em ordem crescente (ASC) ou decrescente (DESC) com base em uma ou mais colunas.
*   `GROUP BY`: **Como** os dados devem ser agrupados. Agrupa os resultados da consulta com base em uma ou mais colunas, frequentemente usado com funções de agregação (COUNT, SUM, AVG, etc.).
*   `LIMIT`: **Quantos** resultados queremos. Limita o número de linhas retornadas pelos resultados da consulta.

## Exemplo de Consulta SQL Simples

```sql
SELECT nome, sobrenome, salario
FROM colaboradores
WHERE departamento = 'vendas';
```